### PR TITLE
#40 Log files are rotated every minute even if datePattern specifies only daily rotation

### PR DESCRIPTION
**Pull request by kumar-b**
Added function which checks the validity of filename based on given datePattern.

### CODE REVIEW

**Comment by mattberther** [comment]
Thanks for your contribution @kumar-b. Im good with this -- however, would you be able to please add a couple tests to validate the functionality?

Thanks!

**Comment by kumar-b** [comment]
Yeah sure. I will add some tests.

**Comment by kumar-b** [comment]
added test cases for log rotation with different patterns.

**Comment by mattberther** [comment]
Merged as a07b8203abf9d630318315ea5274b029aacfc50e. Thanks for your contribution, @kumar-b.

**Pull request closed without merging**
