### PR TITLE
fix: race condition in `file-stream-rotator`

### PR DESCRIPTION
**Pull request by Means88**
Related: #328, https://github.com/rogerc/file-stream-rotator/pull/81

`file-stream-rotator` checks directories with `fs.existsSync(fullPath)` before creating with `fs.mkdirSync(fullPath)`, which contains race condition and throws EEXIST error. 

Create the directory manually before using this package.

### CODE REVIEW

**Comment by Apollon77** [comment]
@mattberther Maybe you have any chance to reach out @rogerc?

**Comment by Means88** [comment]
Closed because rogerc/file-stream-rotator#81 have been merged

**Comment by Apollon77** [comment]
@Means88 But we might need a dep update after the file-stream-rotator npm push because v0.6.0

**Comment by mattberther** [comment]
Yes. The new version has not been pushed to npm and therefore, I cannot update the dependency in winston-daily-rotate-file.

**Comment by Means88** [comment]
Maybe I'll update the dependency after it's released and keep the unit test in this pr?

**Comment by Means88** [comment]
file-stream-rotator@0.6.0 is released, but contains another bug. I'll keep tracking on it. https://github.com/rogerc/file-stream-rotator/pull/87

**Comment by rogerc** [comment]
@Means88 I've published v0.6.1 that fixes the issue of not checking for auditLog. Thanks for PR.

**Comment by Means88** [comment]
Thanks for @rogerc to release the package, I've updated the package in this pr

**Comment by mattberther** [comment]
Thank you for the contribution. Merged to master and published as `winston-daily-rotate-file@4.6.0`.

**Comment by Apollon77** [comment]
Thnal you @mattberther @rogerc @Means88

**Pull request merged**
