### PR TITLE
Add to Winston.transports

### PR DESCRIPTION
**Pull request by perrin4869**
Little addition so as to stay consistent with other plugins

### CODE REVIEW

**Comment by indexzero** [comment]
I am +0 on this. I will see if there is feedback from the rest of the community for this demand.

**Comment by perrin4869** [comment]
Well, I also don't exactly like this syntax either, but it's just the way basically all other plugins, including the build it ones work... I just thought code would look a bit cleaner if all plugins are loaded the same

**Comment by lillem4n** [comment]
I'm +1 to this, my code just broke because I have winston logging configuration in a JSON config file to be able to have it differently between environments. It's a very irritating issue to have them work differently out of the box.

**Comment by mattberther** [comment]
Seems a harmless change that would improve backwards compatibility. Im +1 on this.

**Pull request merged**
