### PR TITLE
fixes https://github.com/winstonjs/winston-daily-rotate-file/issues/125

### PR DESCRIPTION
**Pull request by Apollon77**
... by also checking for gz filename before deleting

### CODE REVIEW

**Comment by Apollon77** [comment]
Sorry it seems my rebase did not worked :-( in fact my change is the first commit only

**Comment by mattberther** [comment]
Thanks @Apollon77. I've cherry picked your commit and merged at https://github.com/winstonjs/winston-daily-rotate-file/commit/e504c1385c1fc7bc7eb82511e182493b4b61fdc4. I'll publish a new version shortly.

**Comment by Apollon77** [comment]
Thank you!

**Comment by mattberther** [comment]
Published `winston-daily-rotate-file@4.4.1` which includes this fix.

**Pull request closed without merging**
