### PR TITLE
Improved filename treatment - Related to issue #55

### PR DESCRIPTION
**Pull request by velenoise**
Added support to extension on file name
Added options to customize separator apart from date format
Added option for default extension, in case it's ommited from the file
name

### CODE REVIEW

**Comment by velenoise** [comment]
I'm not familiar with travis to understand what may have failed, if you want to give me some guidelines I'll be happy to correct my pull request. I'm sure it's working correctly because I implemented it for a live project.

**Comment by mattberther** [comment]
@velenoise thanks for the PR. Can you make sure that the unit tests are passing -- you can do so by running `npm test` from the root of the project. Ill look for an updated commit that makes the tests pass before I merge the PR. 

Thanks!

**Comment by velenoise** [comment]
I've been quite busy with some other stuff, but I'll try to get back to it this week.

**Comment by kiermasp** [comment]
Hi guys, Please can sb merge this ? We have live project where we use this plugin and I really need this feature. Thanks.

**Comment by kiermasp** [comment]
Any chance to get this merged?

**Comment by velenoise** [comment]
@kiermasp Feel free to download from my branch while it's not merged: https://github.com/velenoise/winston-daily-rotate-file/tree/filename-adjustments. It seems some new test checks were included that are failing on my branch now, I'll have to take some time later to review them, but probably it's just that the tests are waiting for the old format as a result.

**Comment by mattberther** [comment]
@velenoise I'd like to get this merged. However, I also need to make sure that we're not changing existing unit tests to make this work. The existing unit tests describe functionality that users of the library may have come to expect.

This may mean that we need to add an option that users can select to leverage your code path.

So, as I see it, there are a couple things left:

- [ ] Revert the code changes to the unit test file(s)
- [ ] Create new unit tests that describe the expected functionality from the PR
- [ ] Update the implementation to make sure ALL unit tests pass
- [ ] Run npm test locally to ensure everything is passing
- [ ] Push the changes to this PR

Thanks!

**Comment by sandman45** [comment]
@velenoise awesome!!! this is what i need :D 

I am using your branch.. once its merged I assume you will delete it? if so is there a way I can get a message or update if I follow it or you? 

thanks

**Comment by mattberther** [comment]
Some long-overdue refactoring of the transport has occurred. Closing this PR in favor of #107.

**Pull request closed without merging**
