### PR TITLE
Use UTC date format to match Winston standard

### LINKED ISSUE #17: DailyRotateFile transport uses local time zone for rotation
> Originally reported by @intraz at https://github.com/winstonjs/winston/issues/456

The DailyRotateFile transport rotates based on the local time zone configured on the machine it is running on. Winston's default time stamps in the log lines are UTC (ISO string).

This means that when the local machine is set to a time zone other than UTC the log file for a given date (as set by DailyRotateFile) might include entries that seem to be from a day before or after (depending on the time zone) when actually they are just described in a different time zone (UTC).

Ideally it (and all other transports) should use the same mechanism used by Winston itself or at least have a standard configuration that makes this issue clear.

### PR DESCRIPTION
**Pull request by brunolemos**
Fix #17

### CODE REVIEW

**Comment by mattberther** [comment]
Thanks for your contribution @brunolemos. Much appreciated!

**Comment by Chetan1302** [comment]
Hi Guys,

I want Dailyrotatefile to follow date pattern as per Local TimeZone how can I configure datepattern ?

Thanks and Regards,
Chetan Raskar

**Comment by mattberther** [comment]
@Chetan1302 updating the date pattern per timezone is not available at this time. Id welcome a PR though ;)

**Comment by mattberther** [comment]
@Chetan1302 Check out #52

**Comment by Chetan1302** [comment]
Thank you mattberther and sorry for the late response.I did not see #52 changes in node module that I installed.Sorry I am new to the system :).How can we track these changes with node module versions ?I am using 1.1.5 Version.

**Comment by mattberther** [comment]
@Chetan1302 v1.3.0 is on pm and should have these changes.

**Pull request merged**
