### PR TITLE
Reintroduce namespace and correct import/export

### LINKED ISSUE #246: Typings broken after 4.2.0
After v4.2.0 with the "big" typings change, basically everything broke. Was this even tested?

```
$ rimraf dist && tsc
../../node_modules/winston-daily-rotate-file/index.d.ts:1:8 - error TS1259: Module '"/home/runner/work/***/***/node_modules/winston-transport/index"' can only be default-imported using the 'esModuleInterop' flag

1 import TransportStream from "winston-transport";
         ~~~~~~~~~~~~~~~

  ../../node_modules/winston-transport/index.d.ts:37:1
    37 export = TransportStream;
       ~~~~~~~~~~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.

util/logger.ts:55:7 - error TS2351: This expression is not constructable.
  Type 'typeof import("/home/runner/work/***/***/node_modules/winston-daily-rotate-file/index")' has no construct signatures.

55  	new DailyRotateFile({
    	    ~~~~~~~~~~~~~~~
```

Reading this should be pretty evident whats happening here. So lets go over this, first one? I can't really do anything against, the import is simply wrong because `winston-transport` does not export a default.
https://github.com/winstonjs/winston-daily-rotate-file/blob/21fa56519bf64fbde90baa6ec74c4020b0d08a00/index.d.ts#L1

https://github.com/winstonjs/winston-transport/blob/46db8f3c8cd8b106ade8d7e04a191ee388683d60/index.d.ts#L37

Not everyone uses esModuleInterop so relying on this is quite bad.

Now what about the 2nd one. Not being able to construct DailyRotateFile? But I imported it just fine with `import * as DailyRotateFile from 'winston-daily-rotate-file';` before 4.2.0

Well this is actually incorrect in the typings, they say:
https://github.com/winstonjs/winston-daily-rotate-file/blob/21fa56519bf64fbde90baa6ec74c4020b0d08a00/index.d.ts#L106

But in reality:
https://github.com/winstonjs/winston-daily-rotate-file/blob/21fa56519bf64fbde90baa6ec74c4020b0d08a00/index.js#L6-L7

And even after fixing all of those, I can't go back to the intended way of calling `import * as DailyRotatefile from 'x';` because:
`This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.`

Mainly because of how the typings file is written now.

### PR DESCRIPTION
**Pull request by Slessi**
Fixes #246 

@mattberther this would be patch release, poor review on my part from last MR

### CODE REVIEW

**Comment by mattberther** [comment]
Thanks @Slessi. Does this still address the items from @BubbleBear?

**Comment by Slessi** [comment]
@mattberther yes, but ive realised it doesnt fix the issue i tagged >.> working on it

**Comment by Slessi** [comment]
@mattberther ok, we good now :pray:

**Comment by mattberther** [comment]
Thank you. Merging now.

**Comment by BubbleBear** [comment]
> Thanks @Slessi. Does this still address the items from @BubbleBear?

sorry for the late reply... i was on national holiday, and didn't check my email nor github.

**Comment by BubbleBear** [comment]
this was definitely a fetal mistake made by me. sorry, i'll take all blames. :(

**Pull request merged**
