### PR TITLE
#20 zippedArchive working with DailyRotateFile by @pataiadam

### PR DESCRIPTION
**Pull request by mattberther**
Winston pull request by @pataiadam https://github.com/winstonjs/winston/pull/675

Pull request created based on list at #2

### CODE REVIEW

**Comment by gliesche** [comment]
Is there any plan to merge this in the near future?

**Comment by mattberther** [comment]
@gliesche I need to get back to this - there have been some changes in master that conflict with this.

**Comment by gliesche** [comment]
@mattberther That'd be great!

**Comment by mattberther** [comment]
Closed in favor of #63

**Pull request closed without merging**
