### PR TITLE
add clean old log files

### PR DESCRIPTION
**Pull request by amcereijo**
I'm using your module for my apps.
I have a need to remove old log files(several days before).
I added the possibility to configure the owner app to ask for remove old log files.

If you think this could be a good option for your module, take a look at the PR and if you like confirm it.

### CODE REVIEW

**Comment by amcereijo** [comment]
I just fixed the eslint problems

**Comment by tilleul** [comment]
Could this feature be merged and be made available on npm ?

**Comment by amcereijo** [comment]
Yes, it fact I'm using a generated version in my private npm repository. So
have this change available in the oficial npm repository would be great.

Thank you

**Comment by mattberther** [comment]
Thank you for your contribution, @amcereijo. Merged and pushed to npm as 1.5.0.

**Pull request merged**
