### PR TITLE
Add Information for es6, ts

### PR DESCRIPTION
**Pull request by Adekoreday**
Add Information to enable users get started in 

- TS
- ES6

As mentioned in this issue 

[Issue 207](https://github.com/winstonjs/winston-daily-rotate-file/issues/207#issuecomment-856163094)

### CODE REVIEW

**Comment by Adekoreday** [comment]
hello @mattberther made a PR for this let me know your thoughts
CC 
@Zamiell

**Comment by Zamiell** [comment]
seems good

**Comment by Zamiell** [comment]
From this documentation, I can't help but notice the glaring use of side effects.
But I guess that's a separate issue: https://github.com/winstonjs/winston-daily-rotate-file/issues/321

**Comment by mattberther** [comment]
Thank you. Merged as https://github.com/winstonjs/winston-daily-rotate-file/commit/aa46174d1647c319fbf2981aa2353f098b30a51c

**Pull request closed without merging**
