### PR TITLE
converting vows tests to mocha and adding eslint

### PR DESCRIPTION
**Pull request by mattberther**

### CODE REVIEW

**Comment by indexzero** [comment]
Awesome job @mattberther!

**Comment by mattberther** [comment]
thanks @indexzero. 

BTW: At some point, Id like to be able to push new versions out to npm. I asked on the `winston` project PR as well, but thought Id ask here too.

Any chance you could add me as an owner of the winston-daily-rotate-file package on npm?

```
npm owner add mattberther winston-daily-rotate-file
```

**Comment by indexzero** [comment]
Done. We're looking for new maintainers for `winston` as well. We meet Monday & Tuesday for an hour every other week if you're interested.

**Comment by mattberther** [comment]
Thanks!

Interested, yes. Can I sit in on a meeting or two just to get a feel for the time involved before I commit?

**Comment by indexzero** [comment]
@mattberther absolutely. Will add you to the meeting invites for next time.

**Pull request merged**
